### ISSUE TITLE
File Automatic Issues

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template_Website#51]
would it include- have a github user account, verified the account on email, install Git Kraken (if you are new to pull requests) and link Git Kraken to your github account?

@cansavvy moving the checklist discussion here

**Comment by cansavvy** [comment]
Yes. I think any step that's involved should have a checklist point. Maybe this would be a good item for @howardbaek to address so he becomes more familiar with OTTR?

**Comment by cansavvy** [comment]
Automatic issues can be made by having template issues like this: https://github.com/jhudsl/OTTR_Template/tree/main/.github/automatic-issues

And then a GitHub action that has code like this: https://github.com/jhudsl/OTTR_Template/blob/aeb942738344df76f62903fe582d22b227c49b48/.github/workflows/starting-course.yml#L91

@howardbaek could you take this information and make a github action that would file automatic issues upon the creation of a new OTTR website? 

The last step of the github action should include deleting the github action yaml file itself (because this would only be run once upon the creation of a new website with the OTTR_Template_Website. 

Let me know what questions you have!
